spring.datasource.url=${MYSQL_JDBC_URL:jdbc:mysql://localhost:3306/librarymanager}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:211006}
#spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:21062/railway
#spring.datasource.username=root
#spring.datasource.password=HHaXSuJfRCDVPCtFNRZtYpyftDJcNolW
jwt.secret=${JWT_SECRET:abc1234567890abc1234567890abcdef}
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:./
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=16MB

# Gmail SMTP for OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:taioccho203@gmail.com}
spring.mail.password=${MAIL_PASSWORD:bpikzxglqaqjbpsf}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
