spring.datasource.url=${MYSQL_JDBC_URL:jdbc:mysql://yamanote.proxy.rlwy.net:21062/railway}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:HHaXSuJfRCDVPCtFNRZtYpyftDJcNolW}
jwt.secret=${JWT_SECRET:abc1234567890abc1234567890abcdef}
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,file:./
